server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      package-to-scan: com.nuke
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
  sql:
    init:
      mode: always
  main:
    web-application-type: servlet

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5332/customer
#    username: root
#    password: password
#  jpa:
#    defer-datasource-initializer: true
#    hibernate:
#      ddl-auto: create
#      properties:
#        hibernate:
#
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          format_sql: true
#      show-sql: true
#  sql:
#    init:
#      mode: always
#  main:
#    web-application-type: servlet

